config/routes.rb
Rails.application.routes.draw do
  resources :questions#, only: %i[index new edit create update destroy show]
  
  #get '/questions', to: 'questions#index'

  #get '/questions/new', to: 'questions#new'

  #get '/questions/:id/edit', to: 'questions#edit'

  #post '/questions', to: 'questions#create'

  
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
  def formatted_created_at
    created_at.strftime("%Y-%m-%d %H:%M:%S")
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
    @question = Question.find_by id: params[:id]
  end

  def destroy
    @question = Question.find_by id: params[:id]
    @question.destroy
    redirect_to questions_path
  end

  def edit
    @question = Question.find_by id: params[:id]
  end

  def update
    @question = Question.find_by id: params[:id]
    if @question.update question_params
      redirect_to questions_path
    else
      render :edit
    end
  end

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AskIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Questions", questions_path %></li>
      </ul>
    </nav>  
  
    <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to AskIt</h1>

&copy; @alcoder <%= Time.now.year %>

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, required: true, minlength: 2, placeholder: "Title" %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body, required: true, minlength: 2 %>
  </div>

  <%= f.submit "Submit question" %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>


<%= render 'form' %>

app/views/questions/index.html.erb
<h1>Questions</h1>
 
<%= @questions.each do |question| %>
  <h2><%= question.title %></h2>
  <time datetime="<%= question.formatted_created_at %>">
    <%= question.formatted_created_at %>
  </time>
  <p>
    <%= question.body %>
    <br>
    <%= link_to 'Show', question_path(question) %> |
    <%= link_to 'Edit', edit_question_path(question) %> |
    <%= link_to 'Destroy',  question_path(question), data: {method: :delete, confirm: 'Are you sure?'} %>
  </p>
<% end %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h1><%= @question.title %>
<p>
  <time datetime="<%= @question.formatted_created_at %>">
    <%= @question.formatted_created_at %>
  </time>
  <br>
  <%= @question.body %>
</p>